
stages:
  - build

# Generic template to build docker images
.build:docker: &build_docker
 image: docker:latest
 stage: build
 variables:
  DOCKER_DRIVER: overlay
 services:
  - docker:dind
 tags:
  - docker
  - shared

# Build docker images with the "latest" tag
build:docker:latest:
 <<: *build_docker
 only:
  - master
 script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  - docker build -t $CI_REGISTRY_IMAGE:latest .
  - docker push $CI_REGISTRY_IMAGE:latest

# Build docker images with the git tag
build:docker:tags:
 <<: *build_docker
 only:
  - tags
 script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
  - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
